name: Build Puerts NativeAssets

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: windows-2022
            platform: win
            arch: x64
          - os: windows-2022
            platform: win
            arch: ia32
          - os: macos-latest
            platform: osx
            arch: x64
          - os: macos-latest
            platform: osx
            arch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install libc++-dev (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Build puerts native library
        run: |
          ls && tree
          cd ./unity/native
          node ../../cli make --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: puerts-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            ./puerts/**/build_${{ matrix.platform }}_${{ matrix.arch }}_*/Release/*.dll
            ./puerts/**/build_${{ matrix.platform }}_${{ matrix.arch }}_*/Release/*.dylib
            ./puerts/**/build_${{ matrix.platform }}_${{ matrix.arch }}_*/lib*.so
